### ISSUE TITLE
`{check && <div />}` throws XSS error

### ISSUE THREAD

**Issue by arthurfiorette** [kitajs/ts-html-plugin#24]
`{check && <div />}` throws XSS error and should not

**Comment by Firerer** [comment]
```tsx
const Test: Html.Component = () => {
  const a: boolean = true;
  return <div> {a && <div> </div>}</div>;
}
```

**Comment by Firerer** [comment]
my current work around is  `{check ? <div /> : ""}` :(

**Comment by arthurfiorette** [comment]
`{check && (<div />)}` also works

**Comment by arthurfiorette** [comment]
Fixed!

**Comment by Firerer** [comment]
I'm still getting the same error with `<div>{true && <div></div>}</div>` using the latest version, but `{ true && <div />; }` works fine.

```
❯ node -v && pnpm -v
v20.5.1
8.5.1
```

`
"@kitajs/ts-html-plugin": "^1.3.1",
"@kitajs/html": "^3.0.8",
`

**Comment by arthurfiorette** [comment]
Conditions like `text !== '/' ? && <div />` also does not work

**Comment by arthurfiorette** [comment]
I think its fixed now.
